# Note: Replace password (and possibly username) with a string
POST http://localhost:3003/api/login
Content-Type: application/json

{
  "username": "username",
  "password": <password>
}

###

# Wrong password, should return 401
POST http://localhost:3003/api/login
Content-Type: application/json

{
  "username": "username",
  "password": "This is definitely the wrong password"
}

###

# Wrong username, should return 401
POST http://localhost:3003/api/login
Content-Type: application/json

{
  "username": "thisisdefinitelynotavalidusername",
  "password": <password>
}
